# Generated by Django 5.0.1 on 2024-02-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp_4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
